FROM alpine:3.20 AS base

RUN addgroup -S qredin && adduser -S qredin -G qredin

RUN mkdir -p /var/lib/qredin/keys /var/run/qredin /etc/qredin && \
    chown -R qredin:qredin /var/lib/qredin /var/run/qredin /etc/qredin

FROM base AS server

COPY bin/qredin-server /usr/local/bin/qredin-server
COPY deploy/config/server.dev.yaml /etc/qredin/server.yaml

USER qredin:qredin

EXPOSE 443 9090

ENTRYPOINT ["/usr/local/bin/qredin-server"]
CMD ["--config", "/etc/qredin/server.yaml"]