// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: api/workloadapi/v1/workloadapi.proto

package workloadapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadAPI_FetchX509SVID_FullMethodName      = "/workloadapi.v1.WorkloadAPI/FetchX509SVID"
	WorkloadAPI_FetchJWTSVID_FullMethodName       = "/workloadapi.v1.WorkloadAPI/FetchJWTSVID"
	WorkloadAPI_FetchBundle_FullMethodName        = "/workloadapi.v1.WorkloadAPI/FetchBundle"
	WorkloadAPI_SubscribeX509SVIDs_FullMethodName = "/workloadapi.v1.WorkloadAPI/SubscribeX509SVIDs"
	WorkloadAPI_SubscribeJWTSVIDs_FullMethodName  = "/workloadapi.v1.WorkloadAPI/SubscribeJWTSVIDs"
	WorkloadAPI_SubscribeBundles_FullMethodName   = "/workloadapi.v1.WorkloadAPI/SubscribeBundles"
)

// WorkloadAPIClient is the client API for WorkloadAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadAPIClient interface {
	FetchX509SVID(ctx context.Context, in *X509SVIDRequest, opts ...grpc.CallOption) (*X509SVIDResponse, error)
	FetchJWTSVID(ctx context.Context, in *JWTSVIDRequest, opts ...grpc.CallOption) (*JWTSVIDResponse, error)
	FetchBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*BundleResponse, error)
	SubscribeX509SVIDs(ctx context.Context, in *SubscribeX509SVIDsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeX509SVIDsResponse], error)
	SubscribeJWTSVIDs(ctx context.Context, in *SubscribeJWTSVIDsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeJWTSVIDsResponse], error)
	SubscribeBundles(ctx context.Context, in *SubscribeBundlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeBundlesResponse], error)
}

type workloadAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadAPIClient(cc grpc.ClientConnInterface) WorkloadAPIClient {
	return &workloadAPIClient{cc}
}

func (c *workloadAPIClient) FetchX509SVID(ctx context.Context, in *X509SVIDRequest, opts ...grpc.CallOption) (*X509SVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(X509SVIDResponse)
	err := c.cc.Invoke(ctx, WorkloadAPI_FetchX509SVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadAPIClient) FetchJWTSVID(ctx context.Context, in *JWTSVIDRequest, opts ...grpc.CallOption) (*JWTSVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWTSVIDResponse)
	err := c.cc.Invoke(ctx, WorkloadAPI_FetchJWTSVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadAPIClient) FetchBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*BundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BundleResponse)
	err := c.cc.Invoke(ctx, WorkloadAPI_FetchBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadAPIClient) SubscribeX509SVIDs(ctx context.Context, in *SubscribeX509SVIDsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeX509SVIDsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadAPI_ServiceDesc.Streams[0], WorkloadAPI_SubscribeX509SVIDs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeX509SVIDsRequest, SubscribeX509SVIDsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeX509SVIDsClient = grpc.ServerStreamingClient[SubscribeX509SVIDsResponse]

func (c *workloadAPIClient) SubscribeJWTSVIDs(ctx context.Context, in *SubscribeJWTSVIDsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeJWTSVIDsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadAPI_ServiceDesc.Streams[1], WorkloadAPI_SubscribeJWTSVIDs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeJWTSVIDsRequest, SubscribeJWTSVIDsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeJWTSVIDsClient = grpc.ServerStreamingClient[SubscribeJWTSVIDsResponse]

func (c *workloadAPIClient) SubscribeBundles(ctx context.Context, in *SubscribeBundlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeBundlesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadAPI_ServiceDesc.Streams[2], WorkloadAPI_SubscribeBundles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeBundlesRequest, SubscribeBundlesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeBundlesClient = grpc.ServerStreamingClient[SubscribeBundlesResponse]

// WorkloadAPIServer is the server API for WorkloadAPI service.
// All implementations must embed UnimplementedWorkloadAPIServer
// for forward compatibility.
type WorkloadAPIServer interface {
	FetchX509SVID(context.Context, *X509SVIDRequest) (*X509SVIDResponse, error)
	FetchJWTSVID(context.Context, *JWTSVIDRequest) (*JWTSVIDResponse, error)
	FetchBundle(context.Context, *BundleRequest) (*BundleResponse, error)
	SubscribeX509SVIDs(*SubscribeX509SVIDsRequest, grpc.ServerStreamingServer[SubscribeX509SVIDsResponse]) error
	SubscribeJWTSVIDs(*SubscribeJWTSVIDsRequest, grpc.ServerStreamingServer[SubscribeJWTSVIDsResponse]) error
	SubscribeBundles(*SubscribeBundlesRequest, grpc.ServerStreamingServer[SubscribeBundlesResponse]) error
	mustEmbedUnimplementedWorkloadAPIServer()
}

// UnimplementedWorkloadAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadAPIServer struct{}

func (UnimplementedWorkloadAPIServer) FetchX509SVID(context.Context, *X509SVIDRequest) (*X509SVIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchX509SVID not implemented")
}
func (UnimplementedWorkloadAPIServer) FetchJWTSVID(context.Context, *JWTSVIDRequest) (*JWTSVIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchJWTSVID not implemented")
}
func (UnimplementedWorkloadAPIServer) FetchBundle(context.Context, *BundleRequest) (*BundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchBundle not implemented")
}
func (UnimplementedWorkloadAPIServer) SubscribeX509SVIDs(*SubscribeX509SVIDsRequest, grpc.ServerStreamingServer[SubscribeX509SVIDsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeX509SVIDs not implemented")
}
func (UnimplementedWorkloadAPIServer) SubscribeJWTSVIDs(*SubscribeJWTSVIDsRequest, grpc.ServerStreamingServer[SubscribeJWTSVIDsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeJWTSVIDs not implemented")
}
func (UnimplementedWorkloadAPIServer) SubscribeBundles(*SubscribeBundlesRequest, grpc.ServerStreamingServer[SubscribeBundlesResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBundles not implemented")
}
func (UnimplementedWorkloadAPIServer) mustEmbedUnimplementedWorkloadAPIServer() {}
func (UnimplementedWorkloadAPIServer) testEmbeddedByValue()                     {}

// UnsafeWorkloadAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadAPIServer will
// result in compilation errors.
type UnsafeWorkloadAPIServer interface {
	mustEmbedUnimplementedWorkloadAPIServer()
}

func RegisterWorkloadAPIServer(s grpc.ServiceRegistrar, srv WorkloadAPIServer) {
	// If the following call panics, it indicates UnimplementedWorkloadAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadAPI_ServiceDesc, srv)
}

func _WorkloadAPI_FetchX509SVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(X509SVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadAPIServer).FetchX509SVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadAPI_FetchX509SVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadAPIServer).FetchX509SVID(ctx, req.(*X509SVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadAPI_FetchJWTSVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWTSVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadAPIServer).FetchJWTSVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadAPI_FetchJWTSVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadAPIServer).FetchJWTSVID(ctx, req.(*JWTSVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadAPI_FetchBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadAPIServer).FetchBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadAPI_FetchBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadAPIServer).FetchBundle(ctx, req.(*BundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadAPI_SubscribeX509SVIDs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeX509SVIDsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadAPIServer).SubscribeX509SVIDs(m, &grpc.GenericServerStream[SubscribeX509SVIDsRequest, SubscribeX509SVIDsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeX509SVIDsServer = grpc.ServerStreamingServer[SubscribeX509SVIDsResponse]

func _WorkloadAPI_SubscribeJWTSVIDs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeJWTSVIDsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadAPIServer).SubscribeJWTSVIDs(m, &grpc.GenericServerStream[SubscribeJWTSVIDsRequest, SubscribeJWTSVIDsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeJWTSVIDsServer = grpc.ServerStreamingServer[SubscribeJWTSVIDsResponse]

func _WorkloadAPI_SubscribeBundles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeBundlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadAPIServer).SubscribeBundles(m, &grpc.GenericServerStream[SubscribeBundlesRequest, SubscribeBundlesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadAPI_SubscribeBundlesServer = grpc.ServerStreamingServer[SubscribeBundlesResponse]

// WorkloadAPI_ServiceDesc is the grpc.ServiceDesc for WorkloadAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workloadapi.v1.WorkloadAPI",
	HandlerType: (*WorkloadAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchX509SVID",
			Handler:    _WorkloadAPI_FetchX509SVID_Handler,
		},
		{
			MethodName: "FetchJWTSVID",
			Handler:    _WorkloadAPI_FetchJWTSVID_Handler,
		},
		{
			MethodName: "FetchBundle",
			Handler:    _WorkloadAPI_FetchBundle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeX509SVIDs",
			Handler:       _WorkloadAPI_SubscribeX509SVIDs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeJWTSVIDs",
			Handler:       _WorkloadAPI_SubscribeJWTSVIDs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBundles",
			Handler:       _WorkloadAPI_SubscribeBundles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/workloadapi/v1/workloadapi.proto",
}
