// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: api/workloadapi/v1/workloadapi.proto

package workloadapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type X509SVID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiffeId      string                 `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	CertChain     []byte                 `protobuf:"bytes,2,opt,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509SVID) Reset() {
	*x = X509SVID{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVID) ProtoMessage() {}

func (x *X509SVID) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVID.ProtoReflect.Descriptor instead.
func (*X509SVID) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{0}
}

func (x *X509SVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *X509SVID) GetCertChain() []byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *X509SVID) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *X509SVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type JWTSVID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiffeId      string                 `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hint          string                 `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSVID) Reset() {
	*x = JWTSVID{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSVID) ProtoMessage() {}

func (x *JWTSVID) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSVID.ProtoReflect.Descriptor instead.
func (*JWTSVID) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{1}
}

func (x *JWTSVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *JWTSVID) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JWTSVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type Bundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain     string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	X509Authorities []byte                 `protobuf:"bytes,2,opt,name=x509_authorities,json=x509Authorities,proto3" json:"x509_authorities,omitempty"`
	JwtAuthorities  []byte                 `protobuf:"bytes,3,opt,name=jwt_authorities,json=jwtAuthorities,proto3" json:"jwt_authorities,omitempty"`
	Hint            string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{2}
}

func (x *Bundle) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *Bundle) GetX509Authorities() []byte {
	if x != nil {
		return x.X509Authorities
	}
	return nil
}

func (x *Bundle) GetJwtAuthorities() []byte {
	if x != nil {
		return x.JwtAuthorities
	}
	return nil
}

func (x *Bundle) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type X509SVIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509SVIDRequest) Reset() {
	*x = X509SVIDRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVIDRequest) ProtoMessage() {}

func (x *X509SVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVIDRequest.ProtoReflect.Descriptor instead.
func (*X509SVIDRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{3}
}

func (x *X509SVIDRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type JWTSVIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSVIDRequest) Reset() {
	*x = JWTSVIDRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSVIDRequest) ProtoMessage() {}

func (x *JWTSVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSVIDRequest.ProtoReflect.Descriptor instead.
func (*JWTSVIDRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{4}
}

func (x *JWTSVIDRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type X509SVIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svids         []*X509SVID            `protobuf:"bytes,1,rep,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509SVIDResponse) Reset() {
	*x = X509SVIDResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVIDResponse) ProtoMessage() {}

func (x *X509SVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVIDResponse.ProtoReflect.Descriptor instead.
func (*X509SVIDResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{5}
}

func (x *X509SVIDResponse) GetSvids() []*X509SVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

type JWTSVIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svids         []*JWTSVID             `protobuf:"bytes,1,rep,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSVIDResponse) Reset() {
	*x = JWTSVIDResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSVIDResponse) ProtoMessage() {}

func (x *JWTSVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSVIDResponse.ProtoReflect.Descriptor instead.
func (*JWTSVIDResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{6}
}

func (x *JWTSVIDResponse) GetSvids() []*JWTSVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

type BundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleRequest) Reset() {
	*x = BundleRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleRequest) ProtoMessage() {}

func (x *BundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleRequest.ProtoReflect.Descriptor instead.
func (*BundleRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{7}
}

func (x *BundleRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type BundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundles       []*Bundle              `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleResponse) Reset() {
	*x = BundleResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleResponse) ProtoMessage() {}

func (x *BundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleResponse.ProtoReflect.Descriptor instead.
func (*BundleResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{8}
}

func (x *BundleResponse) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type SubscribeX509SVIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeX509SVIDsRequest) Reset() {
	*x = SubscribeX509SVIDsRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeX509SVIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeX509SVIDsRequest) ProtoMessage() {}

func (x *SubscribeX509SVIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeX509SVIDsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeX509SVIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeX509SVIDsRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type SubscribeJWTSVIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audiences     []string               `protobuf:"bytes,1,rep,name=audiences,proto3" json:"audiences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeJWTSVIDsRequest) Reset() {
	*x = SubscribeJWTSVIDsRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeJWTSVIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeJWTSVIDsRequest) ProtoMessage() {}

func (x *SubscribeJWTSVIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeJWTSVIDsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeJWTSVIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeJWTSVIDsRequest) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

type SubscribeBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBundlesRequest) Reset() {
	*x = SubscribeBundlesRequest{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBundlesRequest) ProtoMessage() {}

func (x *SubscribeBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBundlesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeBundlesRequest) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{11}
}

type SubscribeX509SVIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svids         *X509SVIDResponse      `protobuf:"bytes,1,opt,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeX509SVIDsResponse) Reset() {
	*x = SubscribeX509SVIDsResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeX509SVIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeX509SVIDsResponse) ProtoMessage() {}

func (x *SubscribeX509SVIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeX509SVIDsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeX509SVIDsResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeX509SVIDsResponse) GetSvids() *X509SVIDResponse {
	if x != nil {
		return x.Svids
	}
	return nil
}

type SubscribeJWTSVIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svids         *JWTSVIDResponse       `protobuf:"bytes,1,opt,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeJWTSVIDsResponse) Reset() {
	*x = SubscribeJWTSVIDsResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeJWTSVIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeJWTSVIDsResponse) ProtoMessage() {}

func (x *SubscribeJWTSVIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeJWTSVIDsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeJWTSVIDsResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeJWTSVIDsResponse) GetSvids() *JWTSVIDResponse {
	if x != nil {
		return x.Svids
	}
	return nil
}

type SubscribeBundlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundles       *BundleResponse        `protobuf:"bytes,1,opt,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBundlesResponse) Reset() {
	*x = SubscribeBundlesResponse{}
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBundlesResponse) ProtoMessage() {}

func (x *SubscribeBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workloadapi_v1_workloadapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBundlesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeBundlesResponse) Descriptor() ([]byte, []int) {
	return file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeBundlesResponse) GetBundles() *BundleResponse {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_api_workloadapi_v1_workloadapi_proto protoreflect.FileDescriptor

const file_api_workloadapi_v1_workloadapi_proto_rawDesc = "" +
	"\n" +
	"$api/workloadapi/v1/workloadapi.proto\x12\x0eworkloadapi.v1\"{\n" +
	"\bX509SVID\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x02 \x01(\fR\tcertChain\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"P\n" +
	"\aJWTSVID\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\"\x93\x01\n" +
	"\x06Bundle\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12)\n" +
	"\x10x509_authorities\x18\x02 \x01(\fR\x0fx509Authorities\x12'\n" +
	"\x0fjwt_authorities\x18\x03 \x01(\fR\x0ejwtAuthorities\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"4\n" +
	"\x0fX509SVIDRequest\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\",\n" +
	"\x0eJWTSVIDRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\"B\n" +
	"\x10X509SVIDResponse\x12.\n" +
	"\x05svids\x18\x01 \x03(\v2\x18.workloadapi.v1.X509SVIDR\x05svids\"@\n" +
	"\x0fJWTSVIDResponse\x12-\n" +
	"\x05svids\x18\x01 \x03(\v2\x17.workloadapi.v1.JWTSVIDR\x05svids\"2\n" +
	"\rBundleRequest\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\"B\n" +
	"\x0eBundleResponse\x120\n" +
	"\abundles\x18\x01 \x03(\v2\x16.workloadapi.v1.BundleR\abundles\">\n" +
	"\x19SubscribeX509SVIDsRequest\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\"8\n" +
	"\x18SubscribeJWTSVIDsRequest\x12\x1c\n" +
	"\taudiences\x18\x01 \x03(\tR\taudiences\"\x19\n" +
	"\x17SubscribeBundlesRequest\"T\n" +
	"\x1aSubscribeX509SVIDsResponse\x126\n" +
	"\x05svids\x18\x01 \x01(\v2 .workloadapi.v1.X509SVIDResponseR\x05svids\"R\n" +
	"\x19SubscribeJWTSVIDsResponse\x125\n" +
	"\x05svids\x18\x01 \x01(\v2\x1f.workloadapi.v1.JWTSVIDResponseR\x05svids\"T\n" +
	"\x18SubscribeBundlesResponse\x128\n" +
	"\abundles\x18\x01 \x01(\v2\x1e.workloadapi.v1.BundleResponseR\abundles2\xc4\x04\n" +
	"\vWorkloadAPI\x12R\n" +
	"\rFetchX509SVID\x12\x1f.workloadapi.v1.X509SVIDRequest\x1a .workloadapi.v1.X509SVIDResponse\x12O\n" +
	"\fFetchJWTSVID\x12\x1e.workloadapi.v1.JWTSVIDRequest\x1a\x1f.workloadapi.v1.JWTSVIDResponse\x12L\n" +
	"\vFetchBundle\x12\x1d.workloadapi.v1.BundleRequest\x1a\x1e.workloadapi.v1.BundleResponse\x12m\n" +
	"\x12SubscribeX509SVIDs\x12).workloadapi.v1.SubscribeX509SVIDsRequest\x1a*.workloadapi.v1.SubscribeX509SVIDsResponse0\x01\x12j\n" +
	"\x11SubscribeJWTSVIDs\x12(.workloadapi.v1.SubscribeJWTSVIDsRequest\x1a).workloadapi.v1.SubscribeJWTSVIDsResponse0\x01\x12g\n" +
	"\x10SubscribeBundles\x12'.workloadapi.v1.SubscribeBundlesRequest\x1a(.workloadapi.v1.SubscribeBundlesResponse0\x01B9Z7github.com/qredin/qredin/api/workloadapi/v1;workloadapib\x06proto3"

var (
	file_api_workloadapi_v1_workloadapi_proto_rawDescOnce sync.Once
	file_api_workloadapi_v1_workloadapi_proto_rawDescData []byte
)

func file_api_workloadapi_v1_workloadapi_proto_rawDescGZIP() []byte {
	file_api_workloadapi_v1_workloadapi_proto_rawDescOnce.Do(func() {
		file_api_workloadapi_v1_workloadapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_workloadapi_v1_workloadapi_proto_rawDesc), len(file_api_workloadapi_v1_workloadapi_proto_rawDesc)))
	})
	return file_api_workloadapi_v1_workloadapi_proto_rawDescData
}

var file_api_workloadapi_v1_workloadapi_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_workloadapi_v1_workloadapi_proto_goTypes = []any{
	(*X509SVID)(nil),                   // 0: workloadapi.v1.X509SVID
	(*JWTSVID)(nil),                    // 1: workloadapi.v1.JWTSVID
	(*Bundle)(nil),                     // 2: workloadapi.v1.Bundle
	(*X509SVIDRequest)(nil),            // 3: workloadapi.v1.X509SVIDRequest
	(*JWTSVIDRequest)(nil),             // 4: workloadapi.v1.JWTSVIDRequest
	(*X509SVIDResponse)(nil),           // 5: workloadapi.v1.X509SVIDResponse
	(*JWTSVIDResponse)(nil),            // 6: workloadapi.v1.JWTSVIDResponse
	(*BundleRequest)(nil),              // 7: workloadapi.v1.BundleRequest
	(*BundleResponse)(nil),             // 8: workloadapi.v1.BundleResponse
	(*SubscribeX509SVIDsRequest)(nil),  // 9: workloadapi.v1.SubscribeX509SVIDsRequest
	(*SubscribeJWTSVIDsRequest)(nil),   // 10: workloadapi.v1.SubscribeJWTSVIDsRequest
	(*SubscribeBundlesRequest)(nil),    // 11: workloadapi.v1.SubscribeBundlesRequest
	(*SubscribeX509SVIDsResponse)(nil), // 12: workloadapi.v1.SubscribeX509SVIDsResponse
	(*SubscribeJWTSVIDsResponse)(nil),  // 13: workloadapi.v1.SubscribeJWTSVIDsResponse
	(*SubscribeBundlesResponse)(nil),   // 14: workloadapi.v1.SubscribeBundlesResponse
}
var file_api_workloadapi_v1_workloadapi_proto_depIdxs = []int32{
	0,  // 0: workloadapi.v1.X509SVIDResponse.svids:type_name -> workloadapi.v1.X509SVID
	1,  // 1: workloadapi.v1.JWTSVIDResponse.svids:type_name -> workloadapi.v1.JWTSVID
	2,  // 2: workloadapi.v1.BundleResponse.bundles:type_name -> workloadapi.v1.Bundle
	5,  // 3: workloadapi.v1.SubscribeX509SVIDsResponse.svids:type_name -> workloadapi.v1.X509SVIDResponse
	6,  // 4: workloadapi.v1.SubscribeJWTSVIDsResponse.svids:type_name -> workloadapi.v1.JWTSVIDResponse
	8,  // 5: workloadapi.v1.SubscribeBundlesResponse.bundles:type_name -> workloadapi.v1.BundleResponse
	3,  // 6: workloadapi.v1.WorkloadAPI.FetchX509SVID:input_type -> workloadapi.v1.X509SVIDRequest
	4,  // 7: workloadapi.v1.WorkloadAPI.FetchJWTSVID:input_type -> workloadapi.v1.JWTSVIDRequest
	7,  // 8: workloadapi.v1.WorkloadAPI.FetchBundle:input_type -> workloadapi.v1.BundleRequest
	9,  // 9: workloadapi.v1.WorkloadAPI.SubscribeX509SVIDs:input_type -> workloadapi.v1.SubscribeX509SVIDsRequest
	10, // 10: workloadapi.v1.WorkloadAPI.SubscribeJWTSVIDs:input_type -> workloadapi.v1.SubscribeJWTSVIDsRequest
	11, // 11: workloadapi.v1.WorkloadAPI.SubscribeBundles:input_type -> workloadapi.v1.SubscribeBundlesRequest
	5,  // 12: workloadapi.v1.WorkloadAPI.FetchX509SVID:output_type -> workloadapi.v1.X509SVIDResponse
	6,  // 13: workloadapi.v1.WorkloadAPI.FetchJWTSVID:output_type -> workloadapi.v1.JWTSVIDResponse
	8,  // 14: workloadapi.v1.WorkloadAPI.FetchBundle:output_type -> workloadapi.v1.BundleResponse
	12, // 15: workloadapi.v1.WorkloadAPI.SubscribeX509SVIDs:output_type -> workloadapi.v1.SubscribeX509SVIDsResponse
	13, // 16: workloadapi.v1.WorkloadAPI.SubscribeJWTSVIDs:output_type -> workloadapi.v1.SubscribeJWTSVIDsResponse
	14, // 17: workloadapi.v1.WorkloadAPI.SubscribeBundles:output_type -> workloadapi.v1.SubscribeBundlesResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_workloadapi_v1_workloadapi_proto_init() }
func file_api_workloadapi_v1_workloadapi_proto_init() {
	if File_api_workloadapi_v1_workloadapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_workloadapi_v1_workloadapi_proto_rawDesc), len(file_api_workloadapi_v1_workloadapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_workloadapi_v1_workloadapi_proto_goTypes,
		DependencyIndexes: file_api_workloadapi_v1_workloadapi_proto_depIdxs,
		MessageInfos:      file_api_workloadapi_v1_workloadapi_proto_msgTypes,
	}.Build()
	File_api_workloadapi_v1_workloadapi_proto = out.File
	file_api_workloadapi_v1_workloadapi_proto_goTypes = nil
	file_api_workloadapi_v1_workloadapi_proto_depIdxs = nil
}
